---
title: "R Notebook"
output: html_notebook
---


```{r}
# Group the data by month and sum the sales for each month
MARKETDaily <- MARKET %>%
  mutate(Day = floor_date(Day, "day")) %>%
  group_by(Day) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# create xts time series object
MARKETDailyts <- xts(MARKETDaily$Sales, order.by = MARKETDaily$Day)


PlotMARKET <- dygraph(MARKETDailyts)%>%
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesOpts = list(strokeWidth = 3)) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(8, "Dark2")) %>%
  dyLegend(show = "always") 
PlotMARKET
```




```{r}
# Group the data by month and sum the sales for each month
MARKETDept <- MARKET %>%
  mutate(Day = floor_date(Day, "day")) %>%
  group_by(Day, Department) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# Reshape the data from long to wide format
MARKETDept <- dcast(MARKETDept, Department  ~  Day, value.var = "Sales") %>% select(1,29,28,27,26,25,24,23,22,21,20,19,18,17) %>% arrange(desc(`2023-06-18`))
# Format the salary column as custom accounting values

MARKETDept$`2023-06-18` <- format(MARKETDept$`2023-06-18`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-17` <- format(MARKETDept$`2023-06-17`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-16` <- format(MARKETDept$`2023-06-16`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-15` <- format(MARKETDept$`2023-06-15`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-14` <- format(MARKETDept$`2023-06-14`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-13` <- format(MARKETDept$`2023-06-13`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-12` <- format(MARKETDept$`2023-06-12`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-11` <- format(MARKETDept$`2023-06-11`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-10` <- format(MARKETDept$`2023-06-10`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-09` <- format(MARKETDept$`2023-06-09`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-08` <- format(MARKETDept$`2023-06-08`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-07` <- format(MARKETDept$`2023-06-07`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDept$`2023-06-06` <- format(MARKETDept$`2023-06-06`, big.mark = ",", decimal.mark = ".", nsmall = 0)




MARKETDept

```


```{r}
# Group the data by month and sum the sales for each month
MARKETCategory <- MARKET %>%
  mutate(Day = floor_date(Day, "day")) %>%
  group_by(Day, Category) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# Reshape the data from long to wide format
MARKETCategory <- dcast(MARKETCategory, Category  ~  Day, value.var = "Sales") %>% select(1,29,28,27,26,25,24,23,22,21,20,19,18,17) %>% arrange(desc(`2023-06-18`))
# Format the salary column as custom accounting values



MARKETCategory$`2023-06-18` <- format(MARKETCategory$`2023-06-18`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-17` <- format(MARKETCategory$`2023-06-17`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-16` <- format(MARKETCategory$`2023-06-16`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-15` <- format(MARKETCategory$`2023-06-15`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-14` <- format(MARKETCategory$`2023-06-14`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-13` <- format(MARKETCategory$`2023-06-13`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-12` <- format(MARKETCategory$`2023-06-12`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-11` <- format(MARKETCategory$`2023-06-11`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-10` <- format(MARKETCategory$`2023-06-10`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-09` <- format(MARKETCategory$`2023-06-09`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-08` <- format(MARKETCategory$`2023-06-08`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-07` <- format(MARKETCategory$`2023-06-07`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategory$`2023-06-06` <- format(MARKETCategory$`2023-06-06`, big.mark = ",", decimal.mark = ".", nsmall = 0)


MARKETCategory

```


```{r}
# Group the data by month and sum the sales for each month
MARKETDeptwk <- MARKET %>%
  mutate(week = floor_date(Day, "week")) %>%
  group_by(week, Department) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# Reshape the data from long to wide format
MARKETDeptwk <- dcast(MARKETDeptwk, Department  ~  week, value.var = "Sales") %>% select(1,5,4,3,2) %>% arrange(desc(`2023-06-11`))
# Format the salary column as custom accounting values


MARKETDeptwk$`2023-06-11` <- format(MARKETDeptwk$`2023-06-11`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDeptwk$`2023-06-04` <- format(MARKETDeptwk$`2023-06-04`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDeptwk$`2023-05-28` <- format(MARKETDeptwk$`2023-05-28`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETDeptwk$`2023-05-21` <- format(MARKETDeptwk$`2023-05-21`, big.mark = ",", decimal.mark = ".", nsmall = 0)





MARKETDeptwk
```

```{r}
# Group the data by month and sum the sales for each month
MARKETCategorywk <- MARKET %>%
  mutate(week = floor_date(Day, "week")) %>%
  group_by(week, Category) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# Reshape the data from long to wide format
MARKETCategorywk <- dcast(MARKETCategorywk, Category  ~  week, value.var = "Sales") %>% select(1,5,4,3,2) %>% arrange(desc(`2023-06-11`))
# Format the salary column as custom accounting values


MARKETCategorywk$`2023-06-11` <- format(MARKETCategorywk$`2023-06-11`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategorywk$`2023-06-04` <- format(MARKETCategorywk$`2023-06-04`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategorywk$`2023-05-28` <- format(MARKETCategorywk$`2023-05-28`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MARKETCategorywk$`2023-05-21` <- format(MARKETCategorywk$`2023-05-21`, big.mark = ",", decimal.mark = ".", nsmall = 0)

MARKETCategorywk

```