---
title: "R Notebook"
output: html_notebook
---

 
```{r}
# Group the data by month and sum the sales for each month
MLOLONGODaily <- MLOLONGO %>%
  mutate(Day = floor_date(Day, "day")) %>%
  group_by(Day) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# create xts time series object
MLOLONGODailyts <- xts(MLOLONGODaily$Sales, order.by = MLOLONGODaily$Day)


PlotMLOLONGO <- dygraph(MLOLONGODailyts)%>%
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesOpts = list(strokeWidth = 3)) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(8, "Dark2")) %>%
  dyLegend(show = "always") 
PlotMLOLONGO
```




```{r}
# Group the data by month and sum the sales for each month
MLOLONGODept <- MLOLONGO %>%
  mutate(Day = floor_date(Day, "day")) %>%
  group_by(Day, Department) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# Reshape the data from long to wide format
MLOLONGODept <- dcast(MLOLONGODept, Department  ~  Day, value.var = "Sales") %>% select(1,29,28,27,26,25,24,23,22,21,20,19,18,17) %>% arrange(desc(`2023-06-18`))
# Format the salary column as custom accounting values

MLOLONGODept$`2023-06-18` <- format(MLOLONGODept$`2023-06-18`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-17` <- format(MLOLONGODept$`2023-06-17`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-16` <- format(MLOLONGODept$`2023-06-16`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-15` <- format(MLOLONGODept$`2023-06-15`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-14` <- format(MLOLONGODept$`2023-06-14`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-13` <- format(MLOLONGODept$`2023-06-13`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-12` <- format(MLOLONGODept$`2023-06-12`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-11` <- format(MLOLONGODept$`2023-06-11`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-10` <- format(MLOLONGODept$`2023-06-10`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-09` <- format(MLOLONGODept$`2023-06-09`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-08` <- format(MLOLONGODept$`2023-06-08`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-07` <- format(MLOLONGODept$`2023-06-07`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODept$`2023-06-06` <- format(MLOLONGODept$`2023-06-06`, big.mark = ",", decimal.mark = ".", nsmall = 0)




MLOLONGODept

```


```{r}
# Group the data by month and sum the sales for each month
MLOLONGOCategory <- MLOLONGO %>%
  mutate(Day = floor_date(Day, "day")) %>%
  group_by(Day, Category) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# Reshape the data from long to wide format
MLOLONGOCategory <- dcast(MLOLONGOCategory, Category  ~  Day, value.var = "Sales") %>% select(1,29,28,27,26,25,24,23,22,21,20,19,18,17) %>% arrange(desc(`2023-06-18`))
# Format the salary column as custom accounting values



MLOLONGOCategory$`2023-06-18` <- format(MLOLONGOCategory$`2023-06-18`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-17` <- format(MLOLONGOCategory$`2023-06-17`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-16` <- format(MLOLONGOCategory$`2023-06-16`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-15` <- format(MLOLONGOCategory$`2023-06-15`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-14` <- format(MLOLONGOCategory$`2023-06-14`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-13` <- format(MLOLONGOCategory$`2023-06-13`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-12` <- format(MLOLONGOCategory$`2023-06-12`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-11` <- format(MLOLONGOCategory$`2023-06-11`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-10` <- format(MLOLONGOCategory$`2023-06-10`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-09` <- format(MLOLONGOCategory$`2023-06-09`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-08` <- format(MLOLONGOCategory$`2023-06-08`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-07` <- format(MLOLONGOCategory$`2023-06-07`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategory$`2023-06-06` <- format(MLOLONGOCategory$`2023-06-06`, big.mark = ",", decimal.mark = ".", nsmall = 0)


MLOLONGOCategory

```


```{r}
# Group the data by month and sum the sales for each month
MLOLONGODeptwk <- MLOLONGO %>%
  mutate(week = floor_date(Day, "week")) %>%
  group_by(week, Department) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# Reshape the data from long to wide format
MLOLONGODeptwk <- dcast(MLOLONGODeptwk, Department  ~  week, value.var = "Sales") %>% select(1,5,4,3,2) %>% arrange(desc(`2023-06-11`))
# Format the salary column as custom accounting values


MLOLONGODeptwk$`2023-06-11` <- format(MLOLONGODeptwk$`2023-06-11`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODeptwk$`2023-06-04` <- format(MLOLONGODeptwk$`2023-06-04`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODeptwk$`2023-05-28` <- format(MLOLONGODeptwk$`2023-05-28`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGODeptwk$`2023-05-21` <- format(MLOLONGODeptwk$`2023-05-21`, big.mark = ",", decimal.mark = ".", nsmall = 0)





MLOLONGODeptwk
```

```{r}
# Group the data by month and sum the sales for each month
MLOLONGOCategorywk <- MLOLONGO %>%
  mutate(week = floor_date(Day, "week")) %>%
  group_by(week, Category) %>%
  summarize(Sales = sum(Sum.of.Total.Sales)) 

# Reshape the data from long to wide format
MLOLONGOCategorywk <- dcast(MLOLONGOCategorywk, Category  ~  week, value.var = "Sales") %>% select(1,5,4,3,2) %>% arrange(desc(`2023-06-11`))
# Format the salary column as custom accounting values


MLOLONGOCategorywk$`2023-06-11` <- format(MLOLONGOCategorywk$`2023-06-11`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategorywk$`2023-06-04` <- format(MLOLONGOCategorywk$`2023-06-04`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategorywk$`2023-05-28` <- format(MLOLONGOCategorywk$`2023-05-28`, big.mark = ",", decimal.mark = ".", nsmall = 0)
MLOLONGOCategorywk$`2023-05-21` <- format(MLOLONGOCategorywk$`2023-05-21`, big.mark = ",", decimal.mark = ".", nsmall = 0)

MLOLONGOCategorywk

```